### ISSUE TITLE
Errors with self signed SSL Cert

### ISSUE THREAD

**Issue by f4nk9** [bTayFla/PtTracker#172]
seems like self signet certs are not supported

error log level debug:

```
Something went wrong while fetching data from ProfitTrailer. Be sure to check that the ProfitTrailer WebUrl and ServerApiToken settings are correct.
 message=Error: self signed certificate
				, name=RequestError
				, code=DEPTH_ZERO_SELF_SIGNED_CERT
				, $ref=$["cause"], uri=https://localhost:myport/api/data?token=myapitoken
				, callback=function RP$callback(err, response, body) {plumbing.callback.call(self, err, response, body);}
				, transform=undefined
				, simple=true
				, resolveWithFullResponse=false
				, transform2xxOnly=false
				, response=undefined
				, stack=RequestError: Error:	
				self signed certificate
				at new RequestError (/snapshot/PtTracker/node_modules/request-promise-core/lib/errors.js:14:15)
				at Request.module.exports.plumbing.callback (/snapshot/PtTracker/node_modules/request-promise-core/lib/plumbing.js:87:29)
				at Request.RP$callback [as _callback] (/snapshot/PtTracker/node_modules/request-promise-core/lib/plumbing.js:46:31)
				at Request.init.self.callback (/snapshot/PtTracker/node_modules/request/request.js:185:22)
				at emitOne (events.js:116:13)
				at Request.emit (events.js:211:7)
				at Request.onRequestError (/snapshot/PtTracker/node_modules/request/request.js:881:8)
				at emitOne (events.js:116:13)
				at ClientRequest.emit (events.js:211:7)
				at TLSSocket.socketErrorListener (_http_client.js:387:9)
				at emitOne (events.js:116:13)
				at TLSSocket.emit (events.js:211:7)
				at emitErrorNT (internal/streams/destroy.js:64:8)
				at _combinedTickCallback (internal/process/next_tick.js:138:11)
				at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by f4nk9** [comment]
Meanwhile I installed my cert on localhost. wget works without any cert errors. ther error log from PTTracker is still the same.

**Comment by LiamAird** [comment]
Helped via discord
