### ISSUE TITLE
[BUG] 2.0.1 still can't connect to PT that's using self-signed certificate

### ISSUE THREAD

**Issue by bruce133** [bTayFla/PtTracker#80]
I reported this to _rireal_ and he purportedly fixed it in 2.0.1, but I still get the same error:

```
17:19:03 - error: Could not login to ProfitTrailer
17:19:03 - debug:  RequestError: Error: self signed certificate
    at new RequestError (/snapshot/PtTracker/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.module.exports.plumbing.callback (/snapshot/PtTracker/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/snapshot/PtTracker/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.init.self.callback (/snapshot/PtTracker/node_modules/request/request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/snapshot/PtTracker/node_modules/request/request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

The 'fix' seemingly involved allowing insecure connections from PtTracker to PT, but I doubt that will work as PT doesn't seem to allow insecure connections when SSL is enabled.

**Comment by hackley2** [comment]
Though this is a work around and not a fix, thought you might find my SSL setup useful:

I am able to use LetsEncrypt SSL keys with both PtTracker v2.0.1 and ProfitTrailer. Are you able to change from using a self signed cert to a LetsEncrypt cert? Since the LetsEncypt service became available I've not come across the need to use self signed certificates. https://letsencrypt.org

Anyway, good luck!

**Comment by clownfish44** [comment]
https://github.com/bTayFla/PtTracker/issues/82

**Comment by bruce133** [comment]
@clownfish44 Why close this issue? It's not the same error as in #82, and he's using a LetsEncrypt certificate, not a self-signed one like I am. And before you tell me to try v2.0.2, I already did.

@hackley2 My bot is within my local network and not accessible from the web, so I believe LetsEncrypt won't work for me as I don't have a proper domain. Thanks for your input though, I appreciate it.

**Comment by clownfish44** [comment]
@bruce133 this is all an ssl issue your saying that self signed does not work and he is saying lets encrypt doesn't work therefore both methods of ssl are broke.

**Comment by bruce133** [comment]
@clownfish44 As a developer I would much rather have these clearly distinct issues (they even had different versions affecting them) separated in the issue tracker, not merged together simply because they fit in the same category. But hey, perhaps that's just me.
